### ISSUE TITLE
勝手にmerge?

### ISSUE THREAD

**Issue by miya4649** [synthesijer/extra-libs#2]
すみません、Pull requestを出したつもりが次々クリックしたら本流にマージされてしまったような気がします。
これで良かったでしょうか？
本来はPull request→承認の流れだと思いますがなぜか自分でmergeしてしまったようです

**Comment by miyo** [comment]
説明が足りていなかったようですみませんなのですが、write権限付与させてもらいましたので、pullできる動作に間違いはないです。

**Comment by miyo** [comment]
私としてはこれでいいかなーと思っているのですが、分けた方がいいですかね。

**Comment by miya4649** [comment]
分けるというとブランチですか？ディレクトリ構成ですか？
先ほどそのマージをリバートしようとしたところ失敗して自分の方のforkでゴミができてしまいました。
miyoxさんの方のファイルがリバートされるような形になったので、そのリバートをリバートして
元の形に戻ったはずですが私の方のforkを見ていただくと分かりますが汚いことになっています。
これは次にpull requestした時はこのゴミ操作もmergeされてしまうでしょうか。
https://github.com/miya4649/extra-libs/commits/master
自動的にrevertブランチもできています。
不慣れですみません

**Comment by miyo** [comment]
"分ける"=直接mergeはできないようにbranchを分ける，という意味でした．
ディレクトリ構成は今のままがいいと思います．
ただbranchを分けたところで，mergeする手間は変わりませんし，
私とmiya4649さんの二人程度の規模でしたら，今の方法でよいのではないかと思っています．

なお，miya4649さんでforkされたものを見てみましたが，
おっしゃるものは，全然ゴミ操作ということはないと思いますし，
そのままpullしていただければと思います．

順序が後先になりましたが，audioライブラリの追加，ありがとうございます!!

**Comment by miya4649** [comment]
分かりました。次回はpull requestを出したところまでで止める形にしようと思います。
ブランチの構成などはおまかせしますので何かこちらで操作が必要でしたら指示してください。
あとドキュメントやライセンス表示、命名規則、ライブラリの構成の仕方など
暫定的な仕様で作っていますが方針やご提案等ありましたらよろしくお願いします。
