### ISSUE TITLE
make synthesijer/sample/bd/TB-7Z-020

### ISSUE THREAD

**Issue by miya4649** [synthesijer/extra-libs#7]
synthesijer/sample/bd/TB-7Z-020 をmakeした時に、以下のようなエラーが出ます。

source: SinTableRom.java
SchdulerBoard init: TestFrame
SchdulerBoard init: SimpleAXIMemIface32RTLTest
SchdulerBoard init: RGBTest
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: .SinTableRom
	at synthesijer.Manager.loadUserHDLModule(Manager.java:315)
	at synthesijer.Manager.compileSchedulerInfo(Manager.java:335)
	at synthesijer.Manager.compileSchedulerInfoAll(Manager.java:321)
	at synthesijer.Manager.generate(Manager.java:388)
	at synthesijer.Main.main(Main.java:165)
Caused by: java.lang.ClassNotFoundException: .SinTableRom
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at synthesijer.Manager.loadUserHDLModule(Manager.java:306)
	... 4 more
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by miyo** [comment]
ご報告ありがとうございます．先日のパッケージ関連の取扱いで「パッケージが指定されていないHDLModuleを継承したクラス」への対応が不十分でした．
https://github.com/synthesijer/synthesijer/commit/a91a0d295649da95368a1e9fb0112b83202ebd04
で修正しました．

**Comment by miya4649** [comment]
ありがとうございます。
synthesijer/sample/bd/TB-7Z-020 のmakeが通ることを確認しました。
以下は一通りサンプルをmakeしてみて気づいた部分です。（irohaは試していません）

・多くのサンプルで、make clean で *.irが消えません。

・以下のサンプルで、MakefileのSYNTHESIJER, SYNTHESIJER_EXTRA_LIB, SYNTHESIJER_LIB 等の初期値が実際のものとは異なっています。

synthesijer/sample/bd/Zybo/axiburst_test
synthesijer/sample/bd/Zybo/quickstart
synthesijer/sample/bd/zynq/axi_test

特に、synthesijer/sample/bd/zynq/axi_testは
「SYNTHESIJER_EXTRA_LIB =」と上書き設定になっているので.bashrcなどで環境変数を設定していてもmakeに失敗します。

extra-libsの私の作成したサンプルも環境変数の初期値が合っていないので、後で修正します。

**Comment by miya4649** [comment]
もう一つ気づいたこと、というか質問になりますが、
以前はextra-libsをコンパイルした時の出力ファイル名が
synthesijer_lib_axi_SimpleAXIMemIface32RTLTest.v
などになっていたと思うのですが、現在は
SimpleAXIMemIface32RTLTest.vという短い名前になっていますが、
これは仕様になりますでしょうか。

**Comment by miyo** [comment]
ロング名が適切です．見落としです．ありがとうございます．
仕様の明確化と検証をまじめに考えないといけないですね．コメントありがとうございます．

**Comment by miya4649** [comment]
分かりました。私のサンプルのMakefileの環境変数の方はすでに修正しましたがファイル名はそのままにしておきます。

**Comment by miyo** [comment]
パッケージ名含むロングネームでモジュール作るように修正しました．
https://github.com/synthesijer/synthesijer/commit/b0b834a8ed364357cca830116bed23a5b6d9e831

- audio_output_example
- free_run_counter_example
- led_array_example

は，makeできることを確認しました．
ところで，@miya4649 さんのMakefileだとreadme.txtも消えてしまうので，ちょっとだけ修正しました（すみません，pushしてしまいました）

**Comment by miya4649** [comment]
そんな風になってましたか！全然気が付きませんでしたｗありがとうございます。
readme.mdがあったらreadme.txtはいらないかも知れませんね。
重複してると更新が手間ですしreadme.mdに統一しましょうか？

**Comment by miyo** [comment]
readme的なものは.mdの方が見栄えがいいかな，と思いますが，お好みでえらんでいただければ．
現在，スケジューリング過程を.txtに吐いているのですが，.txtは一般的すぎるのでどこかのタイミングで別の拡張子にしようとは思っています．

**Comment by miya4649** [comment]
分かりました。最近はmdが一般的になっているのでreadme.mdに統一しようと思います。
私の方でreadme.mdを少し修正しておきます。

**Comment by miya4649** [comment]
Makefileを見るとreadme.txtが消えないように工夫されていますが、
同じ内容のreadme.mdを追加されたのはなぜでしょうか。
もしかして何かのツールで自動生成されたものですか？

**Comment by miyo** [comment]
説明が全然足りてませんでした．すみません．readme.txtが消えないように工夫するか，readme.mdに移行するかどっちかだなあ，と考えているままに，pushしてしまったのでした．特にツールで作ったわけではないです．

**Comment by miya4649** [comment]
分かりました。mdも実質.txtと同じようにテキストエディタで読めますし、
GitHubできれいに表示されるのでやはりmdが良さそうかと思います。

**Comment by miyo** [comment]
了解です．引き続きよろしくおねがいします．私も，readme.txtはreadme.mdに置き換えていく方向ですすめようと思います．
